language: swift
osx_image: xcode8.2
xcode_project: Test_ci.xcodeproj
#xcode_project: Test_ci.xcworkspace
xcode_scheme: Test_ci
xcode_sdk: iphonesimulator8.4
#scripts:
#  - xcodebuild -scheme Test_ci -workspace Test_ci.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.2' buil test
after_success:
 - bash <(curl -s https://codecov.io/bash)

